# Generated by Django 6.0.6 on 2026-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
