# Generated by Django 6.0.6 on 2026-07-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_alter_venue_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuemedia",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="venues.venue",
            ),
        ),
    ]
