# Generated by Django 6.0.6 on 2026-07-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_alter_venuemedia_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuemedia",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venue_media",
                to="venues.venue",
            ),
        ),
    ]
