# Generated by Django 6.0.6 on 2026-07-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="venues.venue",
            ),
        ),
        migrations.AddField(
            model_name="bookingfacility",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_facilities",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingfacility",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="venues.facility"
            ),
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_services",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="venues.service"
            ),
        ),
    ]
